// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Models;

#nullable disable

namespace GPAPI.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220923083336_VerlofUpdate")]
    partial class VerlofUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("GPAPI.Models.Medewerker", b =>
                {
                    b.Property<int>("MedewerkerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wachtwoord")
                        .HasColumnType("TEXT");

                    b.HasKey("MedewerkerID");

                    b.ToTable("Medewerkers");
                });

            modelBuilder.Entity("GPAPI.Models.Verlof", b =>
                {
                    b.Property<int>("VerlofID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MedewerkerID")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Tot")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Van")
                        .HasColumnType("INTEGER");

                    b.HasKey("VerlofID");

                    b.HasIndex("MedewerkerID");

                    b.ToTable("Verlof");
                });

            modelBuilder.Entity("GPAPI.Models.Verlof", b =>
                {
                    b.HasOne("GPAPI.Models.Medewerker", "Medewerker")
                        .WithMany("Verlofs")
                        .HasForeignKey("MedewerkerID");

                    b.Navigation("Medewerker");
                });

            modelBuilder.Entity("GPAPI.Models.Medewerker", b =>
                {
                    b.Navigation("Verlofs");
                });
#pragma warning restore 612, 618
        }
    }
}
